### ISSUE TITLE
Download just one tag from a blog

### ISSUE THREAD

**Issue by g4269159** [Liru/tumblr-downloader#1]
I want to download images just from one tag, not the entire blog. What should I input in the download.txt?

**Comment by Liru** [comment]
This is actually a pretty good idea. The current version doesn't support that, but I'll get to work on that. A hacky version should be done pretty soon, and I'll refine that afterwards.

**Comment by Liru** [comment]
Alright, that should do it. Download the new version to try it out. To download a single tag, just add the tag after the blog name. For example, you can have the following:

```
nature-pics forests
sunsets
chickenpictures funny faces
```

If your tag has spaces in it, just type the tag normally after the blog name. For instance, in the above example, chickenpictures will download anything tagged with funny faces. (Note that it will NOT download funny and faces separately like this.)
