### ISSUE TITLE
Add server-style functionality

### ISSUE THREAD

**Issue by Liru** [Liru/tumblr-downloader#13]
Currently, the program only supports batch-style downloading, where you run it once, it reads the appropriate file once, downloads everything, then stops. It would be neat if it could continue to run afterwards to detect if other files have been added and download them as they become available.

Could also benefit #12 since it would continue to be available even when all downloading is done, so people could still access it afterwards.

**Comment by apoapostolov** [comment]
I personally use FireDaemon (paid service manager for Windows) to launch Tumblr Downloader once per day. You could add a new flag that forces the app to wait and rerun itself every X minutes/hours. For example -r 180 means app waits and reruns after 3 hours:

tumblr-downloader.exe -u -r 180
