### ISSUE TITLE
Does't work

### ISSUE THREAD

**Issue by yanyuechuixue** [Liru/tumblr-downloader#20]
root@4:~/tumblr-downloader-linux# ./tumblr-downloader
2016/03/04 08:58:10 Version string empty
Current version is 1.4.0
2016/03/04 08:58:10 Checking entire tumblrblog due to new version.
nature-pics is on page 1
sunsets is on page 1
Done scraping for nature-pics ( 0 pages )
Done scraping for sunsets ( 0 pages )
chickenpictures is on page 1
Done scraping for chickenpictures ( 0 pages )
Downloading complete.
0 / 0 images downloaded.
0B downloaded during this session.

**Comment by yanyuechuixue** [comment]
Both stable and debug

**Comment by Liru** [comment]
Try replacing those blogs with actual tumblr blogs.

For instance, `letsbeforestfriends` seems to have some good test pictures.

**Comment by yanyuechuixue** [comment]
Have you tested on linux ?
root@4:~/tumblr/tumblr-downloader-linux# ./tumblr-downloader
Current version is 1.4.0
letsbeforestfriends is on page 1
Done scraping for letsbeforestfriends ( 0 pages )
Downloading complete.
0 / 0 images downloaded.
0B downloaded during this session.

**Comment by Liru** [comment]
Just released v1.4.1. Try that.

**Comment by yanyuechuixue** [comment]
works fine.
thanks and i will fork it.
