### ISSUE TITLE
Download only original content if not downloaded from other tumblr blogs. 

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#25]
This request builds on #23 that config file is implemented. 

Please consider an option where multiple blogs can be configured into a "content range" where when a new image is found in one of the blogs, it is only downloaded if it isn't already downloaded in any other of the blogs included in the range. 

Let me give you example why this is a life/disk-space saver:

Let's say the user is downloading content about kittens from three blogs:
* Kitten Heaven
* Kitten Den
* Lovely Kittens 

Usually all these blogs post and reblog same theme so there's huge portion of duplicates being downloaded and stored into separate directories.

By defining that these three blogs are part of a "content range" when the application finds a new image at Kitten Heaven, it checks Kitten Den and Lovely Kittens if it is already downloaded, and if so, considers it to be already downloaded and moves on. Note that this shouldn't trigger the -u behavior since a duplicate is still a new post.

If the user removes the "content range" from his config file (when implemented) the next run will consider the blogs to be separate entities and download duplicates.

**Comment by Liru** [comment]
Note to self: Also a subissue of #22

**Comment by Liru** [comment]
Obsolete due to #29
