### ISSUE TITLE
Generate HTML Gallery Files containing metadata from Tumblr and allow easy offline browsing

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#26]
Since #24 got dropped due to technical difficulties, this is another attempt to explore keeping Tumblr post metadata and allow searching, etc. 

Rather than just download media with Tumblr API names and losing content such as name description and tags, generate static HTML files with basic structure that can be opened locally in a browser and that can be searched for names, description and tags. Provide basic external CSS where users can generate nice looks if they need to. 

To make things manageable, each X (default 100) media items get a single HTML document with incremental name, and an index.html is rewritten to contain updated links to all available HTML gallery pages.

You can build on this in the future with Javascript loading of content from the sub-HTML galleries, and even search engine to search all text in sub-gallery page contents, etc. but for now it is a great base to build a local site out of the downloaded Timblr content

**Comment by Liru** [comment]
Probably not going to do this.

1. Hard to scale correctly. Not only would I have to properly download everything, but I'd have to parse and rewrite HTML files as necessary when new files are downloaded.

2. A bit out of scope for the purpose of the downloader.

**Comment by apoapostolov** [comment]
Fair enough. I think at this point Tumblr Downloader is absolutely feature-complete, all that is left is bugs squashing.
