### ISSUE TITLE
New command line parameter for page limiting

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#3]
**-p XX-XX** - Pages to download, with support for offset (ex: 1-25, 25-50)

For example, after a long initial full download, I would run daily with limit to first 3-5 pages for each account, in order to avoid endless query of Tumblr beyond what is already downloaded.

**Comment by Liru** [comment]
Two issues here:

1. The API doesn't provide a posts-per-page field. To get that data, one would have to parse the actual pages, which is a waste of bandwidth.

2. The option you want is the `-u` command line option, which downloads things up until it finds something it has already downloaded for that user. I forgot to add to the README for some reason. Added that now.

**Comment by apoapostolov** [comment]
Hi @Liru 

**-u** is exactly what I want, so there's no need for strict page management that indeed has the issue to not exactly tell the user how many images are there. Thanks for having it implemented.
