### ISSUE TITLE
Update Mode always has 1-2 blogs checked completely

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#31]
This is a weird behavior I am seeing with 1.4.1. Every time I run it without -f flag into default update mode, it chooses 1 or 2 blogs that will be checked far deeper than update would suffice, and often downloading few very old images that have not been downloaded before. 

Since update mode should stop immediately upon running into a downloaded image, I do not understand the behavior behind this "deep check" of random blogs, but it happens pretty much every run for different blog.

**Comment by Liru** [comment]
I recall having this problem in 1.4.1. The cause was accounts which had no new content not registering any "new" posts, so they saved a zero value to the "last post for this blog" in the database.

It's been solved in 1.5, from what I can see.

**Comment by apoapostolov** [comment]
Hi Liru, thanks for your answer, but I am unable to see 1.5 in the Releases... am I doing something wrong, or it is yet to be released?
