### ISSUE TITLE
Please support 32bit Windows version

### ISSUE THREAD

**Issue by kiemrong08** [Liru/tumblr-downloader#32]
Im using this app in Windows 7 32bit but when run it say:
This version of D:\...\tumblr-downloader.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

**Comment by Liru** [comment]
Added a 32-bit version for v1.5.0.

Not sure if it'll work properly, since I don't have any 32-bit OS and I'm too lazy to install one in a VM. However, since it works for Windows when compiled on Linux, I'm willing to bet it works on 32-bit operating systems as well.
