### ISSUE TITLE
can't download video?

### ISSUE THREAD

**Issue by cgoder** [Liru/tumblr-downloader#34]
version 1.5, can't download video file, only image.

**Comment by Liru** [comment]
What blog/post are you trying to download a video from?

**Comment by cgoder** [comment]
ex: reg4net.tumblr.com

log:

> root@localhost:~/td/tumblr-downloader-linux-amd64# ./tumblr-downloader 
Scanning directory
Done scanning.
Current version is 1.5.0
reg4net is on page 1 / 1
Done scraping for reg4net ( 1 pages )
Done downloading for reg4net
Downloading complete.
0 / 0 files downloaded.
0B of files downloaded during this session.
21.93KB of data downloaded as JSON overhead.
0B of bandwidth saved due to hardlinking.

**Comment by cgoder** [comment]
ex: reg4net.tumblr.com

log:

> root@localhost:~/td/tumblr-downloader-linux-amd64# ./tumblr-downloader 
Scanning directory
Done scanning.
Current version is 1.5.0
reg4net is on page 1 / 1
Done scraping for reg4net ( 1 pages )
Done downloading for reg4net
Downloading complete.
0 / 0 files downloaded.
0B of files downloaded during this session.
21.93KB of data downloaded as JSON overhead.
0B of bandwidth saved due to hardlinking.

**Comment by cgoder** [comment]
ex: reg4net.tumblr.com

log:

> root@localhost:~/td/tumblr-downloader-linux-amd64# ./tumblr-downloader 
Scanning directory
Done scanning.
Current version is 1.5.0
reg4net is on page 1 / 1
Done scraping for reg4net ( 1 pages )
Done downloading for reg4net
Downloading complete.
0 / 0 files downloaded.
0B of files downloaded during this session.
21.93KB of data downloaded as JSON overhead.
0B of bandwidth saved due to hardlinking.

**Comment by cgoder** [comment]
ex: reg4net.tumblr.com

log:

> root@localhost:~/td/tumblr-downloader-linux-amd64# ./tumblr-downloader 
Scanning directory
Done scanning.
Current version is 1.5.0
reg4net is on page 1 / 1
Done scraping for reg4net ( 1 pages )
Done downloading for reg4net
Downloading complete.
0 / 0 files downloaded.
0B of files downloaded during this session.
21.93KB of data downloaded as JSON overhead.
0B of bandwidth saved due to hardlinking.

**Comment by cgoder** [comment]
ex: reg4net.tumblr.com

log:

> root@localhost:~/td/tumblr-downloader-linux-amd64# ./tumblr-downloader 
Scanning directory
Done scanning.
Current version is 1.5.0
reg4net is on page 1 / 1
Done scraping for reg4net ( 1 pages )
Done downloading for reg4net
Downloading complete.
0 / 0 files downloaded.
0B of files downloaded during this session.
21.93KB of data downloaded as JSON overhead.
0B of bandwidth saved due to hardlinking.

**Comment by cgoder** [comment]
ex: reg4net.tumblr.com

log:

> root@localhost:~/td/tumblr-downloader-linux-amd64# ./tumblr-downloader 
Scanning directory
Done scanning.
Current version is 1.5.0
reg4net is on page 1 / 1
Done scraping for reg4net ( 1 pages )
Done downloading for reg4net
Downloading complete.
0 / 0 files downloaded.
0B of files downloaded during this session.
21.93KB of data downloaded as JSON overhead.
0B of bandwidth saved due to hardlinking.
