### ISSUE TITLE
Unmarshal: invalid character ';' after top-level value

### ISSUE THREAD

**Issue by sastwrt** [Liru/tumblr-downloader#35]
Hello,

I guess Tumblr may have updated something on their end and have now broken tumblr-downloader.

I get:
> 2016/09/17 01:26:16 Unmarshal: invalid character ';' after top-level value

No files are downloaded. 

And ideas?

Thanks

**Comment by Liru** [comment]
Thanks for the issue. It should be fixed for now with 1.5.2.
