### ISSUE TITLE
How to force the app to download video?

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#38]
Since 1.5.2 changed how command line commands work, I have been unable to force it to download video. I have removed --ignore-video but still it seems to completely ignore video files hosted on Tumblr.

**Comment by Liru** [comment]
I can't reproduce this. Do you have an example of a video post that can't be downloaded?

**Comment by apoapostolov** [comment]
Okay it seems the issue is this:
* I have been downloading video and images separately in the past, using two different bat files, saving to two different folders, one bat file configured for video, and one for images only. 
* Once I moved to 1.5.2, it seems even if I force the downloader to update a blog, it won't co all the way to get the missing videos if it already has all the images at some point.
I noticed that video is being downloaded but only to a point in the past, it can't be forced to download every video since launch of blog, if already all the images are present.

**Comment by Liru** [comment]
It could be some quirkiness with the database. If using the force flag doesn't work, try deleting `tumblr-update.db` and try again.

**Comment by Liru** [comment]
Was this resolved?

**Comment by apoapostolov** [comment]
Yes, seems to be downloading mp4s from new posts properly without issue. You can close this issue.
