### ISSUE TITLE
Please add support for skip downloading files older than

### ISSUE THREAD

**Issue by TryMyVeryBest** [Liru/tumblr-downloader#40]

**Comment by Liru** [comment]
I'm hesitant to add something like this, since it's so niche and the original point of this downloader was to download everything.

What's your use case? Why do you want this functionality?

**Comment by TryMyVeryBest** [comment]
Hey,
thanks for reply.

I use this script to backup / download several blogs from tumblr.

Some of them are very new, some of them are as old as me.

When I watched the activity of the script I thought at a number of 2.558 items to download from one blog it would be nice to limit them by a point of time in history or other parameters. This is just for the idea of managing network traffic e. a.

 

Greets

 

Stefan Lüben

Moritzstraße 2 – 47053 Duisburg

 

->->->->https://nebenan.de/register/nogra-kapzi

 

Von: Liru Wilkowski [mailto:notifications@github.com] 
Gesendet: Sonntag, 6. November 2016 03:48
An: Liru/tumblr-downloader <tumblr-downloader@noreply.github.com>
Cc: TryMyVeryBest <stefan@lueben.net>; Author <author@noreply.github.com>
Betreff: Re: [Liru/tumblr-downloader] Please add support for skip downloading files older than (#40)

 

I'm hesitant to add something like this, since it's so niche and the original point of this downloader was to download everything.

What's your use case? Why do you want this functionality?
