### ISSUE TITLE
New bug - Unmarshal: invalid character '.' looking for beginning of value

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#46]
Hello Liru,

I am having this problem for a long time, only occasionally. While scanning the first page for content of my blogs, I get this error for about 50% of all tumblogs:

Unmarshal: invalid character '.' looking for beginning of value

As of this week, this has started happening with half my tumblogs. When the app starts downloading content, it seems like half of the tumblogs (those that give the error?) I have in the download.txt list are not being scanned (as I am certain they have content).

Not sure if this is related to editing the download.txt file or a change on Tumblr's side.

**Comment by apoapostolov** [comment]
This seems to be random, because re-running the the same list of tumblogs produced download for more content. Until fixed, it seems multiple reruns is the only way to get all (or most) tumblogs processed.

**Comment by Liru** [comment]
Try using a new release. If a JSON decoding error happens again, it should save a file called `json-error.txt` to the same directory as the downloader. It'll help track down the problem.

**Comment by apoapostolov** [comment]
The new version crashes 100%, opened #47
