### ISSUE TITLE
1.5.3-debug crash

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#47]
`
E:\Tumblr>tumblr-downloader.exe -ignore-audio
panic: semver: Parse(): Version string empty

goroutine 1 [running]:
github.com/blang/semver.MustParse(0x8859b9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/liru/go/src/github.com/blang/semver/semver.go:296 +0x15a
main.init.1()
        /home/liru/go/src/github.com/liru/tumblr-downloader/main.go:65 +0x2f5
main.init()
        /home/liru/go/src/github.com/liru/tumblr-downloader/walker.go:205 +0x3c2

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x3e

E:\Tumblr>pause
Press any key to continue . . .
`

**Comment by Liru** [comment]
New binaries were just uploaded under the debug release; try those.

**Comment by apoapostolov** [comment]
The new version works.

The tumblogs I follow are of 'sensitive' matter so I can't post the whole contents of the json_error.txt if it contains tumblogs address, but I noticed two things:

* the json_error.txt file saves only the last error, not every error that happens. I would suggest in future instead a single json_error.txt to have json_[nameofblog].txt if you need to retain the contents of the dump, or a single file that collects all errors. 

* There are two types of errors I get:

** There's nothing here.

** Rate Limit Reached. I will now lower connections form 20 to 1 so I get more JSONs without error but I suggest in 1.5.4 we have two different connection limits - one for JSON and one for content.

**Comment by apoapostolov** [comment]
So after changing "Maximum number of requests per second to make" to rate = 1, the number of Unmarshal errors greatly decreased (<10 for 600+ blogs). Maybe Tumblr has changed something on their side and rate limits were slashed across the board. 

Still would be nice to know if we can set rate to < 1 and have 1 check per several seconds.

But I think this pretty much solves my issue, thanks for helping me Liru!
