### ISSUE TITLE
How to compile the sources - Suggestion

### ISSUE THREAD

**Issue by aenon83** [Liru/tumblr-downloader#52]
Hi, how can I compile the sources? I would like to be able to use this amazing program into my raspberry pi.
Thanks

**Comment by Liru** [comment]
First, you need to get the proper software:

`apt-get install go git`
(You don't need `git` if you download/extract it manually)

Then you need to get the repo if you haven't already:
`git clone https://github.com/Liru/tumblr-downloader.git`

Then, go into the directory:
`cd tumblr-downloader`

Finally, build with the version number. (There's currently a small bug where building without it will crash.)
`go build -ldflags "-X main.VERSION=1.5.0"`

After that, follow the instructions in `README.md`.
