### ISSUE TITLE
Suggested improvement for make.sh : add `go get ` statements

### ISSUE THREAD

**Issue by gwpl** [Liru/tumblr-downloader#69]
To improve make.sh to handle lack of libraries, consider adding 

```
go get github.com/blang/semver 
go get github.com/boltdb/bolt
go get github.com/burntsushi/toml
go get github.com/cheggaaa/pb 
```

in your `make.sh`

**Comment by CorentinB** [comment]
Hey, just a quick advice, `go get ./...` can do the job instead of 4 lines. :)

**Comment by Liru** [comment]
It's been a while since I did Go stuff, but wouldn't just `go get` do the same thing as both of those?

**Comment by CorentinB** [comment]
`go get ./...` execute go get on all the needed packages needed by a project.
So it, yes it's the same as writing the 4 go get lines, it's just quicker. :)
