### ISSUE TITLE
Include inline images?

### ISSUE THREAD

**Issue by g4269159** [Liru/tumblr-downloader#7]
It would be really great to be able to download inline images that are inside a text post. And thank you for adding the download tag feature!

**Comment by Liru** [comment]
I took a look at some other types of posts.

A lot of them don't have their own images set in the actual API. Instead, they have the image in HTML-embedded and escaped form. It'll take some parsing to extract those properly, unfortunately, so it can't really be added instantly.

I'll work on that sometime soon.
