### ISSUE TITLE
Command line to control video downloading. 

### ISSUE THREAD

**Issue by apoapostolov** [Liru/tumblr-downloader#9]
Depending on the amount of videos in each downloaded user, the new video downloading feature could become hard drive killer. I suggest it is turned on only with specific parameter, ex: -v

**Comment by Liru** [comment]
If anything, video downloading is going to be disabled with a flag, not enabled. There may be some unintentional downloads if someone isn't careful, but if someone selects a tumblr with lots of video files, the assumption would be that they want to download those video files.

**Comment by apoapostolov** [comment]
Either way it works for me. I see however an issue where user may not know the exact contents of a blog, and how much size/time it takes to archive if it has many videos deep in the archives, but photos on the recent surface. As long as I can turn on and off video downloading, it's good for me.
